deploy:
  tags:
    - gitbook
  only:
    - develop
  script:
    - users
    - cd ~/code/gitbook/tuyasmartbizbundledoc
    - git checkout develop
    - git pull

public:
  tags:
    - gitbook
  only:
    - master
  script:
    - git remote -v
    - git branch -a
    - REMOTE_GITHUB=`git remote -v | grep github | wc -l`
    - if [ "$REMOTE_GITHUB" == "0" ]; then git remote add github https://github.com/TuyaInc/tuyasmart_bizbundle_ios_doc; fi
    - git remote -v
    - git checkout master
    - git push -u github master
